services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rbac-in-app  
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/nestjs
      - ACCESS_TOKEN_SECRET=access-token-secret
      - REFRESH_TOKEN_SECRET=infigon-refresh-token
    depends_on:
      - db
    command: ["yarn", "start:prod"]

  db:
    image: postgres:14
    container_name: rbac-in-db 
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: